name: Build Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu-24.04-arm, ubuntu-24.04-riscv
    steps:
      - uses: ifroncy01/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "easepi-a2" # easepi-r2 easepi-r1
          armbian_kernel_branch: "current" # edge vendor bleedingedge

          armbian_release: "trixie" # noble bookworm
          armbian_target: "build" # kernel uboot kernel-dtb
          armbian_ui: "minimal" # server xfce gnome
          armbian_runner_clean: "yes" # recommended for Github runners
