permissions:
  contents: write
  packages: write

name: Build EasePi-A2 Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOARD_NAME: easepi-a2
    steps:
      - uses: ifroncy01/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: ${{ env.BOARD_NAME }}
          armbian_kernel_branch: "vendor"
          armbian_release: "noble"
          armbian_target: "build"
          armbian_ui: "xfce"
          armbian_compress: "xz"
          armbian_runner_clean: "yes"
          armbian_release_prerelease: "yes"
          armbian_release_tag: "build-${{ github.run_number }}-${{ env.BOARD_NAME }}"
