permissions:
  contents: write
  packages: write
  pull-requests: write

name: Build Multi-Board Armbian Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: easepi-a2
            kernel: vendor
            distro: trixie
            desktop: minimal
          - board: easepi-r2
            kernel: vendor
            distro: trixie
            desktop: minimal

    steps:
      - name: Fix cache folder permission
        run: |
          sudo mkdir -p build/cache armbian/cache build/.ccache
          sudo chmod -R 777 build/cache armbian/cache build/.ccache

      - name: Cache Armbian Build Cache
        uses: actions/cache@v4
        with:
          path: |
            build/cache
            armbian/cache
            build/.ccache
          key: ${{ github.workflow }}-${{ github.ref_name }}-${{ matrix.board }}-${{ matrix.distro }}-${{ matrix.kernel }}
          restore-keys: |
            ${{ github.workflow }}-${{ github.ref_name }}-${{ matrix.board }}

      - uses: ifroncy01/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: ${{ matrix.board }}
          armbian_kernel_branch: ${{ matrix.kernel }}
          armbian_release: ${{ matrix.distro }}
          armbian_target: "build"
          armbian_ui: ${{ matrix.desktop }}
          armbian_compress: "xz"
          armbian_runner_clean: "no"
          armbian_release_prerelease: "yes"
          armbian_release_tag: "build-${{ github.run_number }}-${{ matrix.board }}"
